AllCops:
  TargetRubyVersion: 2.7
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
ClassLength:
  Max: 350
