sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.13.0
cache: bundler
script: bundle exec rake
deploy:
  provider: releases
  api_key:
    secure: $TRAVIS_RELEASE_KEY
  file: dist
  on:
    repo: potsbo/anpan
    tags: true
    all_branches: true
