name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install Bundler
        run: gem install bundler -v 1.16.0

      - name: Install dependencies
        run: bundle install
        env:
          BUNDLE_PATH: vendor/bundle

      - name: Run tests
        run: bundle exec rake spec

      - name: Run Rake
        run: bundle exec rake
